version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_WEB_URL: ${FRONTEND_WEB_URL}
      MYSQL_USER: root
    ports:
      - "3306:3306"
    networks:
      - quizapplication
    volumes:
      - mariadb_data:/var/lib/mysql

  minio:
    image: bitnami/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpw
      MINIO_DEFAULT_BUCKETS: files
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - quizapplication

  tomcat:
    image: tomcat:latest
    container_name: tomcat
    ports:
      - "8081:8080"
    volumes:
      - ./target/spring-rest-backend-0.0.1.war:/usr/local/tomcat/webapps/ROOT.war
    networks:
      - quizapplication
    depends_on:
      - mariadb

networks:
  quizapplication:
    driver: bridge

volumes:
  mariadb_data:
  minio_data: